
<? /* @var $oModel Domain\Model\Template */ ?>
<? $oModel = $this->oModel; ?>

<? /* @var $oModel Domain\Collection\Template */ ?>
<? $oList = $oModel->getCollection('list'); ?>

<ul class="submenu">
    <li><a href="/tpl/new">Добавить новый шаблон</a></li>
</ul>

<ul class="list template-list">

<? $index = 0 ?>
<? /* @var $oTpl Domain\Entity\Template */ ?>
<? foreach ($oList AS $oTpl): ?>

    <li><a href="/tpl/<? echo $oTpl->id ?>"><? echo $oTpl->name ?></a> <span class="delete"><a href="/tpl/rm/<? echo $oTpl->id ?>" onclick="return confirm('Нажмите OK, если вы хотите полностью удалить шаблон\n<? echo preg_replace('/[\'"]/ims', '&quot;', $oTpl->name) ?>')">Удалить</a></span></li>

<? endforeach; ?>

</ul>
