<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <title>Regions.ru</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <? $this->headScript()->appendFile("/js/libs/modernizr-2.0.6.min.js", 'text/javascript')->appendFile("/js/script.js", 'text/javascript'); ?>
    <? $this->headLink()->prependStylesheet("/css/style.css"); ?>
    <? echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=UTF-8'); ?>
    <? echo $this->headTitle(); ?>
    <? echo $this->headLink(); ?>
    <? echo $this->headStyle(); ?>
    <? echo $this->headScript(); ?>

    <script defer src="/js/paginator3000.js"></script>
    <link rel="stylesheet" type="text/css" href="/css/paginator3000.css" media="all">
    <!-- Grab Google CDN's jQuery, with a protocol relative URL; fall back to local if offline -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="/js/libs/jquery-1.6.2.min.js"><\/script>')</script>

</head>
<body>

    <div class="header">
        <div class="logo"><img src="/img/sys-logo.png" class="logo" /></div>
        <div class="menu"><? echo $this->MainMenu(); ?></div>
    </div>

</body>
</html>
