<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if IE 9]>    <html class="no-js ie9" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <? echo $this->headTitle(); ?>
    <? echo $this->headMeta(); ?>
    <? echo $this->headLink(); ?>
    <? echo $this->headStyle(); ?>
    <? echo $this->headScript(); ?>
</head>
<body>

    <div class="header">
<!--        <div class="logo"><img src="/img/sys-logo.png" class="logo" /></div>-->
        <div class="menu"><? echo $this->MainMenu(); ?></div>
    </div>

    <div class="content"><? echo $this->layout()->content; ?></div>

</body>
</html>
