
<? /* @var $oModel \Domain\Model\SiteSectionModel */ ?>
<? $oModel = $this->oModel ?>


        <div class="header-content">
            <div class="wrapper990">

                <? echo $this->BreadCrumbs(); ?>
                <? echo $this->MenuSectionSub(); ?>

                <div class="header-content-cols clearfix">

<? $aContainerDefinition = array('<div class="left-header-content-col col">', '<div class="center-header-content-col col">', '<div class="right-header-content-col col">') ?>
<? $index = 0; ?>
<? foreach ($this->EntryGroupFilterByParking($oModel, 'middle-top') AS $oGlock): ?>
    <? echo $aContainerDefinition[$index]; ?>
    <? echo $this->EntryGroupDraw($oGlock) ?>
    <? echo '</div>' ?>
    <? $index++; ?>
<? endforeach; ?>


                </div>
            </div>
        </div>
        <div class="content-cols">
            <div class="wrapper990">
                <div class="left-content-col col">

<? foreach ($this->EntryGroupFilterByParking($oModel, 'middle-left-small') AS $oGlock): ?>
    <? echo $this->EntryGroupDraw($oGlock) ?>
<? endforeach; ?>

                </div>

                <div class="center-content-col col">


                    <div class="col center-content-col1">

<? foreach ($this->EntryGroupFilterByParking($oModel, 'middle-left') AS $oGlock): ?>
    <? echo $this->EntryGroupDraw($oGlock) ?>
<? endforeach; ?>


                    </div>

                    <div class="col center-content-col2">


<? foreach ($this->EntryGroupFilterByParking($oModel, 'middle-center') AS $oGlock): ?>
    <? echo $this->EntryGroupDraw($oGlock) ?>
<? endforeach; ?>


                    </div>

<? if ($middlemiddlebottom = $this->EntryGroupFilterByParking($oModel, 'middle-middle-bottom')): ?>

                    <div class="middle-middle-bottom">

    <? foreach ($middlemiddlebottom AS $oGlock): ?>
        <? echo $this->EntryGroupDraw($oGlock) ?>
    <? endforeach; ?>

                    </div>

<? endif; ?>

                </div>



                <div class="right-content-col col">

<? foreach ($this->EntryGroupFilterByParking($oModel, 'middle-right') AS $oGlock): ?>
    <? echo $this->EntryGroupDraw($oGlock) ?>
<? endforeach; ?>

                </div>

                <div class="clear"></div>
            </div>
        </div>