
<? /* @var $oModel \Domain\Model\UserGroupCategory */ ?>
<? $oModel = $this->oModel; ?>

<? /* @var $oModel Domain\Collection\UserGroupCategory */ ?>
<? $oList = $oModel->getCollection('list'); ?>

<ul class="submenu">
    <li><a href="/group/new">Добавить новую группу</a></li>
</ul>

<ul class="list usergroup-list">

<? $index = 0 ?>
<? /* @var $oGroupCategory Domain\Entity\UserGroupCategory */ ?>
<? foreach ($oList AS $oGroupCategory): ?>
    <? if (!($aGroups = $oGroupCategory->getChilds('group'))): ?>
        <? continue; ?>
    <? endif; ?>

    <li><? echo $oGroupCategory->name ?><ul>

    <? /* @var $oGroup Domain\Entity\UserGroup */ ?>
    <? foreach ($aGroups AS $oGroup): ?>

    <li>
        <a href="/group/<? echo $oGroup->id ?>"><? echo $oGroup->name ?></a>

        <? if ($count = $oGroup->getChildTotalCount('user')): ?>

        <span class="user-count">(<? echo $count ?>)</span>

        <? endif; ?>

        <? if (!$oGroup->algo): ?>

        <span class="delete"><a href="/group/rm/<? echo $oGroup->id ?>" onclick="return confirm('Нажмите OK, если вы хотите полностью удалить группу\n<? echo preg_replace('/[\'"]/ims', '&quot;', $oGroup->name) ?>')">Удалить</a></span>

        <? endif; ?>

    </li>

    <? endforeach; ?>

    </ul></li>

<? endforeach; ?>

</ul>
